"""Schema de reference : la base telle qu'elle existe en production.

Cette revision ne contient AUCUN changement. Elle decrit l'etat atteint par
les `create_all()` successifs, pour donner un point de depart commun :
- une base vierge l'applique et obtient ce schema ;
- la base de production, qui l'a deja, est simplement marquee (`stamp 0001`).

Les evolutions reelles commencent a la revision suivante. Sans ce point fixe,
Alembic ne pourrait pas etre introduit sur une base qui existe deja.

baseline schema

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learned_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "key", name="uq_learned_scope_key"),
    )
    op.create_table(
        "llm_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "response",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "llm_spend",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("calls_real", sa.Integer(), nullable=False),
        sa.Column("calls_cached", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_spend", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_spend_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_spend_created", ["created_at"], unique=False)

    op.create_table(
        "product_corrections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=True),
        sa.Column("row_id", sa.String(length=64), nullable=False),
        sa.Column("field_name", sa.String(length=60), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=10), nullable=False),
        sa.Column("rule", sa.String(length=120), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product_corrections", schema=None) as batch_op:
        batch_op.create_index("ix_corrections_run", ["run_id", "field_name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_product_corrections_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_product_corrections_row_id"), ["row_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_corrections_run_id"), ["run_id"], unique=False)

    op.create_table(
        "review_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("field_name", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("current_value", sa.Text(), nullable=True),
        sa.Column("proposed_value", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("affected_rows", sa.Integer(), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requires_admin", sa.Boolean(), nullable=False),
        sa.Column("decided_by", sa.String(length=36), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_value", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_tasks", schema=None) as batch_op:
        batch_op.create_index("ix_review_status", ["status", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_tasks_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_tasks_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_tasks_store_id"), ["store_id"], unique=False)

    op.create_table(
        "run_anomalies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("row_id", sa.String(length=64), nullable=False),
        sa.Column("field_name", sa.String(length=60), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run_anomalies", schema=None) as batch_op:
        batch_op.create_index("ix_anomalies_run_code", ["run_id", "code"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_anomalies_code"), ["code"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_anomalies_run_id"), ["run_id"], unique=False)

    op.create_table(
        "stores",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "url_check_cache",
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=60), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("url"),
    )
    with op.batch_alter_table("url_check_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_url_check_cache_domain"), ["domain"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=64), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_step", sa.String(length=40), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("rows_in", sa.Integer(), nullable=False),
        sa.Column("rows_out", sa.Integer(), nullable=False),
        sa.Column("publishable_rate", sa.Float(), nullable=False),
        sa.Column(
            "report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("network_enabled", sa.Boolean(), nullable=False),
        sa.Column("triggered_by", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "file_sha256", name="uq_run_store_file"),
    )
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingestion_runs_file_sha256"), ["file_sha256"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ingestion_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_ingestion_runs_store_id"), ["store_id"], unique=False)
        batch_op.create_index("ix_runs_started", ["started_at"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("label", sa.String(length=512), nullable=False),
        sa.Column("label_normalized", sa.String(length=512), nullable=False),
        sa.Column("label_enriched", sa.String(length=512), nullable=True),
        sa.Column("ean", sa.String(length=20), nullable=True),
        sa.Column("internal_code", sa.String(length=40), nullable=True),
        sa.Column("url_image", sa.Text(), nullable=True),
        sa.Column("url_ok", sa.Boolean(), nullable=False),
        sa.Column("url_checked", sa.Boolean(), nullable=False),
        sa.Column("taxonomy_1", sa.String(length=120), nullable=True),
        sa.Column("taxonomy_2", sa.String(length=120), nullable=True),
        sa.Column("taxonomy_3", sa.String(length=120), nullable=True),
        sa.Column("taxonomy_4", sa.String(length=120), nullable=True),
        sa.Column("vat_rate", sa.Float(), nullable=True),
        sa.Column("brand", sa.String(length=120), nullable=True),
        sa.Column("quantity_value", sa.Float(), nullable=True),
        sa.Column("quantity_unit", sa.String(length=10), nullable=True),
        sa.Column("origin", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("publishable", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_rows", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_ean"), ["ean"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_products_label_normalized"), ["label_normalized"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_products_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_products_status", ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_store_id"), ["store_id"], unique=False)
        batch_op.create_index(
            "ix_products_store_label", ["store_id", "label_normalized"], unique=False
        )

    op.create_table(
        "run_steps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("step", sa.String(length=40), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rows_in", sa.Integer(), nullable=False),
        sa.Column("rows_out", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("corrections", sa.Integer(), nullable=False),
        sa.Column("anomalies", sa.Integer(), nullable=False),
        sa.Column(
            "counters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["ingestion_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "step", name="uq_step_per_run"),
    )
    with op.batch_alter_table("run_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_steps_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_steps_run_id"))

    op.drop_table("run_steps")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index("ix_products_store_label")
        batch_op.drop_index(batch_op.f("ix_products_store_id"))
        batch_op.drop_index("ix_products_status")
        batch_op.drop_index(batch_op.f("ix_products_run_id"))
        batch_op.drop_index(batch_op.f("ix_products_label_normalized"))
        batch_op.drop_index(batch_op.f("ix_products_ean"))

    op.drop_table("products")
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_runs_started")
        batch_op.drop_index(batch_op.f("ix_ingestion_runs_store_id"))
        batch_op.drop_index(batch_op.f("ix_ingestion_runs_status"))
        batch_op.drop_index(batch_op.f("ix_ingestion_runs_file_sha256"))

    op.drop_table("ingestion_runs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("url_check_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_url_check_cache_domain"))

    op.drop_table("url_check_cache")
    op.drop_table("stores")
    with op.batch_alter_table("run_anomalies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_anomalies_run_id"))
        batch_op.drop_index(batch_op.f("ix_run_anomalies_code"))
        batch_op.drop_index("ix_anomalies_run_code")

    op.drop_table("run_anomalies")
    with op.batch_alter_table("review_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_tasks_store_id"))
        batch_op.drop_index(batch_op.f("ix_review_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_review_tasks_run_id"))
        batch_op.drop_index("ix_review_status")

    op.drop_table("review_tasks")
    with op.batch_alter_table("product_corrections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_corrections_run_id"))
        batch_op.drop_index(batch_op.f("ix_product_corrections_row_id"))
        batch_op.drop_index(batch_op.f("ix_product_corrections_product_id"))
        batch_op.drop_index("ix_corrections_run")

    op.drop_table("product_corrections")
    with op.batch_alter_table("llm_spend", schema=None) as batch_op:
        batch_op.drop_index("ix_spend_created")
        batch_op.drop_index(batch_op.f("ix_llm_spend_run_id"))

    op.drop_table("llm_spend")
    op.drop_table("llm_cache")
    op.drop_table("learned_rules")
    # ### end Alembic commands ###
