"""Mode de traitement LLM, choisi au depot.

'live' : reponse immediate, plein tarif, pour un depot fait a la main.
'batch' : traitement asynchrone a moitie prix, pour un run que personne ne
regarde. L'arbitrage cout/delai appartient a l'utilisateur, donc il est porte
par le run et non par la configuration du serveur.

Les runs existants prennent 'live' : c'est ce qu'ils ont reellement fait.

mode de traitement LLM par run

Revision ID: 0003
Revises: 0002
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("llm_mode", sa.String(length=10), server_default="live", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.drop_column("llm_mode")

    # ### end Alembic commands ###
