"""Corrections humaines persistantes.

Une valeur corrigee a la main doit survivre au depot du lendemain. Le
referentiel etant recalcule depuis le CSV a chaque integration, une correction
ecrite seulement dans la fiche serait effacee sans prevenir. Elle est donc
stockee comme une decision portant sur la cle naturelle du produit, et rejouee
apres l'etage LLM.

corrections humaines persistantes

Revision ID: 0005
Revises: 0004
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_overrides",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=64), nullable=False),
        sa.Column("product_key", sa.String(length=512), nullable=False),
        sa.Column("field_name", sa.String(length=40), nullable=False),
        sa.Column("previous_value", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "store_id", "product_key", "field_name", name="uq_override_store_key_field"
        ),
    )
    with op.batch_alter_table("product_overrides", schema=None) as batch_op:
        batch_op.create_index("ix_overrides_store", ["store_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_product_overrides_store_id"), ["store_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_overrides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_overrides_store_id"))
        batch_op.drop_index("ix_overrides_store")

    op.drop_table("product_overrides")
    # ### end Alembic commands ###
